title: SSoggyPvP-Manager Documentation
description: PvP toggle plugin with forced zones and playtime-based PvP enforcement
baseurl: "/SSoggyPvP-Manager"
url: ""
theme: jekyll-theme-cayman

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

show_downloads: false

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock